/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanchatRouteImport } from './routes/demo/tanchat'
import { Route as DemoStructuredRouteImport } from './routes/demo/structured'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoImageRouteImport } from './routes/demo/image'
import { Route as DemoCss2026RouteImport } from './routes/demo/css-2026'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTtsRouteImport } from './routes/demo/api.tts'
import { Route as DemoApiTranscriptionRouteImport } from './routes/demo/api.transcription'
import { Route as DemoApiTanchatRouteImport } from './routes/demo/api.tanchat'
import { Route as DemoApiStructuredRouteImport } from './routes/demo/api.structured'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiImageRouteImport } from './routes/demo/api.image'
import { Route as DemoApiAvailableProvidersRouteImport } from './routes/demo/api.available-providers'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanchatRoute = DemoTanchatRouteImport.update({
  id: '/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStructuredRoute = DemoStructuredRouteImport.update({
  id: '/demo/structured',
  path: '/demo/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoImageRoute = DemoImageRouteImport.update({
  id: '/demo/image',
  path: '/demo/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCss2026Route = DemoCss2026RouteImport.update({
  id: '/demo/css-2026',
  path: '/demo/css-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTtsRoute = DemoApiTtsRouteImport.update({
  id: '/demo/api/tts',
  path: '/demo/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTranscriptionRoute = DemoApiTranscriptionRouteImport.update({
  id: '/demo/api/transcription',
  path: '/demo/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTanchatRoute = DemoApiTanchatRouteImport.update({
  id: '/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiStructuredRoute = DemoApiStructuredRouteImport.update({
  id: '/demo/api/structured',
  path: '/demo/api/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiImageRoute = DemoApiImageRouteImport.update({
  id: '/demo/api/image',
  path: '/demo/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAvailableProvidersRoute =
  DemoApiAvailableProvidersRouteImport.update({
    id: '/demo/api/available-providers',
    path: '/demo/api/available-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/css-2026': typeof DemoCss2026Route
  '/demo/image': typeof DemoImageRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/css-2026': typeof DemoCss2026Route
  '/demo/image': typeof DemoImageRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/css-2026': typeof DemoCss2026Route
  '/demo/image': typeof DemoImageRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/css-2026'
    | '/demo/image'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/css-2026'
    | '/demo/image'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/css-2026'
    | '/demo/image'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoCss2026Route: typeof DemoCss2026Route
  DemoImageRoute: typeof DemoImageRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStructuredRoute: typeof DemoStructuredRoute
  DemoTanchatRoute: typeof DemoTanchatRoute
  DemoApiAvailableProvidersRoute: typeof DemoApiAvailableProvidersRoute
  DemoApiImageRoute: typeof DemoApiImageRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiStructuredRoute: typeof DemoApiStructuredRoute
  DemoApiTanchatRoute: typeof DemoApiTanchatRoute
  DemoApiTranscriptionRoute: typeof DemoApiTranscriptionRoute
  DemoApiTtsRoute: typeof DemoApiTtsRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanchat': {
      id: '/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof DemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/structured': {
      id: '/demo/structured'
      path: '/demo/structured'
      fullPath: '/demo/structured'
      preLoaderRoute: typeof DemoStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/image': {
      id: '/demo/image'
      path: '/demo/image'
      fullPath: '/demo/image'
      preLoaderRoute: typeof DemoImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/css-2026': {
      id: '/demo/css-2026'
      path: '/demo/css-2026'
      fullPath: '/demo/css-2026'
      preLoaderRoute: typeof DemoCss2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tts': {
      id: '/demo/api/tts'
      path: '/demo/api/tts'
      fullPath: '/demo/api/tts'
      preLoaderRoute: typeof DemoApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/transcription': {
      id: '/demo/api/transcription'
      path: '/demo/api/transcription'
      fullPath: '/demo/api/transcription'
      preLoaderRoute: typeof DemoApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tanchat': {
      id: '/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof DemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/structured': {
      id: '/demo/api/structured'
      path: '/demo/api/structured'
      fullPath: '/demo/api/structured'
      preLoaderRoute: typeof DemoApiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/image': {
      id: '/demo/api/image'
      path: '/demo/api/image'
      fullPath: '/demo/api/image'
      preLoaderRoute: typeof DemoApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/available-providers': {
      id: '/demo/api/available-providers'
      path: '/demo/api/available-providers'
      fullPath: '/demo/api/available-providers'
      preLoaderRoute: typeof DemoApiAvailableProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoCss2026Route: DemoCss2026Route,
  DemoImageRoute: DemoImageRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStructuredRoute: DemoStructuredRoute,
  DemoTanchatRoute: DemoTanchatRoute,
  DemoApiAvailableProvidersRoute: DemoApiAvailableProvidersRoute,
  DemoApiImageRoute: DemoApiImageRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiStructuredRoute: DemoApiStructuredRoute,
  DemoApiTanchatRoute: DemoApiTanchatRoute,
  DemoApiTranscriptionRoute: DemoApiTranscriptionRoute,
  DemoApiTtsRoute: DemoApiTtsRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
